# Generated by Django 4.2 on 2023-04-27 10:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
